<!-- Bootstrap CSS -->    
<link href="/assets/managerapp/css/bootstrap.min.css" rel="stylesheet">
<!-- bootstrap theme -->
<link href="/assets/managerapp/css/bootstrap-theme.css" rel="stylesheet">
<!--external css-->
<!-- font icon -->
<link href="/assets/managerapp/css/elegant-icons-style.css" rel="stylesheet" />
<link href="/assets/managerapp/css/font-awesome.min.css" rel="stylesheet" />    
<!-- easy pie chart-->
<link href="/assets/managerapp/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>
<!-- owl carousel -->
<link rel="stylesheet" href="/assets/managerapp/css/owl.carousel.css" type="text/css">
<link href="/assets/managerapp/css/jquery-jvectormap-1.2.2.css" rel="stylesheet">
<!-- Custom styles -->
<link rel="stylesheet" href="/assets/managerapp/css/fullcalendar.css">
<link href="/assets/managerapp/css/widgets.css" rel="stylesheet">
<link href="/assets/managerapp/css/style.css" rel="stylesheet">
<link href="/assets/managerapp/css/style-responsive.css" rel="stylesheet" />
<link href="/assets/managerapp/css/xcharts.min.css" rel=" stylesheet">	
<link href="/assets/plugins/jquery-ui-1.10.4/jquery-ui-1.10.4.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/assets/managerapp/alert/dist/sweetalert.css">
<!--datatables-->
<link href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css" rel="stylesheet">
<!-- Append Css file -->
<?php echo $this->headLink(); ?>
<style>
    BODY,ul.dc_mm-orange li a
    {
        font-family: Arial, Helvetica, 'sans-serif' !important;
    }
</style>