<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="/assets/managerapp/js/constant.js"></script>
<script src="/assets/managerapp/alert/dist/sweetalert.min.js"></script>
<!--bootstrap--> 
<script src="/assets/managerapp/js/bootstrap.min.js"></script>
<!--nice scroll--> 
<script src="/assets/managerapp/js/jquery.scrollTo.min.js"></script>
<script src="/assets/managerapp/js/jquery.nicescroll.js" type="text/javascript"></script>
<!--charts scripts--> 
<script src="/assets/managerapp/assets/jquery-knob/js/jquery.knob.js"></script>
<script src="/assets/managerapp/js/jquery.sparkline.js" type="text/javascript"></script>
<!--custom select--> 
<script src="/assets/managerapp/js/jquery.customSelect.min.js" ></script>
<script src="/assets/managerapp/assets/chart-master/Chart.js"></script>
<!--custome script for all page-->
<script src="/assets/managerapp/js/scripts.js"></script>
<!--custom script for this page-->
<script src="/assets/managerapp/js/jquery.autosize.min.js"></script>
<!--datatables--> 
<script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script src="/assets/managerapp/js/bootstrap-datepicker.js"></script>
<!-- Append Js file -->
<?php echo $this->headScript(); ?>