<ul class="nav pull-right top-menu">
    <!-- task notificatoin start -->
    <li id="task_notificatoin_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="/assets/managerapp/#">
            <span class="icon-task-l"></i>
                <span class="badge bg-important">6</span>
        </a>
        <ul class="dropdown-menu extended tasks-bar">
            <div class="notify-arrow notify-arrow-blue"></div>
            <li>
                <p class="blue">You have 6 pending letter</p>
            </li>
            <li>
                <a href="/assets/managerapp/#">
                    <div class="task-info">
                        <div class="desc">Design PSD </div>
                        <div class="percent">90%</div>
                    </div>
                    <div class="progress progress-striped">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                            <span class="sr-only">90% Complete (success)</span>
                        </div>
                    </div>
                </a>
            </li>
            <li class="external">
                <a href="/assets/managerapp/#">See All Tasks</a>
            </li>
        </ul>
    </li>
    <!-- task notificatoin end -->
    <!-- inbox notificatoin start-->
    <li id="mail_notificatoin_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="/assets/managerapp/#">
            <i class="icon-envelope-l"></i>
            <span class="badge bg-important">5</span>
        </a>
        <ul class="dropdown-menu extended inbox">
            <div class="notify-arrow notify-arrow-blue"></div>
            <li>
                <p class="blue">You have 5 new messages</p>
            </li>
            <li>
                <a href="/assets/managerapp/#">
                    <span class="photo"><img alt="avatar" src="/assets/managerapp/./img/avatar-mini.jpg"></span>
                    <span class="subject">
                        <span class="from">Greg  Martin</span>
                        <span class="time">1 min</span>
                    </span>
                    <span class="message">
                        I really like this admin panel.
                    </span>
                </a>
            </li>
            <li>
                <a href="/assets/managerapp/#">See all messages</a>
            </li>
        </ul>
    </li>
    <!-- inbox notificatoin end -->
    <!-- alert notification start-->
    <li id="alert_notificatoin_bar" class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="/assets/managerapp/#">
    
            <i class="icon-bell-l"></i>
            <span class="badge bg-important">7</span>
        </a>
        <ul class="dropdown-menu extended notification">
            <div class="notify-arrow notify-arrow-blue"></div>
            <li>
                <p class="blue">You have 4 new notifications</p>
            </li>
            <li>
                <a href="/assets/managerapp/#">
                    <span class="label label-primary"><i class="icon_profile"></i></span> 
                    Friend Request
                    <span class="small italic pull-right">5 mins</span>
                </a>
            </li>
            <li>
                <a href="/assets/managerapp/#">See all notifications</a>
            </li>
        </ul>
    </li>
    <!-- alert notification end-->
    <!-- user login dropdown start-->
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="/assets/managerapp/#">
            <span class="profile-ava">
                <img alt="" src="/assets/managerapp/img/avatar1_small.jpg">
            </span>
            <span class="username"><?php echo $username ?></span>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu extended logout">
            <div class="log-arrow-up"></div>
            <li class="eborder-top">
                <a href="#"><i class="icon_profile"></i> My Profile</a>
            </li>
            <li>
                <a href="/manageapp/auth/logout"><i class="icon_key_alt"></i> Log Out</a>
            </li>
            <li>
                <a href="#"><i class="icon_key_alt"></i> Documentation</a>
            </li>
        </ul>
    </li>
    <!-- user login dropdown end -->
</ul>