<div class="form-group">
    <label class="col-sm-2 control-label">
        Ảnh đại diện (Càng to càng tốt)<?php if (!empty($this->required)) { ?><span class="required">*</span><?php } ?>
    </label>
    <div class="col-sm-10">
        <div class="fileinput-container">
            <input type="file" name="avatar" class="form-control" <?php if (!empty($this->required)) { ?>required=""<?php } ?> accept="image/*"/>
        </div>
        <img class="img_for_choose" id="avatar" src="<?php echo !empty($this->data['avatar_small']) ? HOME_URL.$this->data['avatar_small'] : HOME_URL."/assets/image/blank.png" ?>" />
    </div>
</div>