<div class="form-group">
    <label class="col-sm-2 control-label">
        Thể loại<?php if (!empty($this->required)) { ?><span class="required">*</span><?php } ?>
       
    </label>
    <div class="col-sm-10">
        <input type="text" name="category" id="category" class="form-control" <?php if (!empty($this->required)) { ?>required=""<?php } ?> 
        value="<?php echo !empty($this->data['category']) ? $this->data['category'] : null; ?>" />
    </div>
</div>