<div class="form-group">
    <label class="control-label col-sm-2">
        Mô tả<?php if (!empty($this->required)) { ?><span class="required">*</span><?php } ?>
    </label>
    <div class="col-sm-10">
        <textarea name="description" id="description" class="form-control" <?php if (!empty($this->required)) { ?>required=""<?php } ?> rows="6"><?php echo !empty($this->data['description']) ? $this->data['description'] : null; ?></textarea>
    </div>
</div>