<div class="form-group">
    <label class="col-sm-2 control-label">
        Tiêu đề<?php if (!empty($this->required)) { ?><span class="required">*</span><?php } ?>
    </label>
    <div class="col-sm-10">
        <input type="text" name="title" id="title" class="form-control" <?php if (!empty($this->required)) { ?>required=""<?php } ?> 
        value="<?php echo !empty($this->data['title']) ? $this->data['title'] : null; ?>" />
    </div>
</div>