<?php 
    echo $this->partial('/partial/notification.phtml', array(
        'error'     => !empty($this->error) ? $this->error : '',
        'warning'   => !empty($this->warning) ? $this->warning : '',
        'success'   => !empty($this->success) ? $this->success : ''
    )); 
?>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Nhập nội dung truyện
            </header>
    
            <div class="panel-body">
                <form class="form-horizontal form-validate form_content" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="id" id="id" value="<?php echo !empty($this->id) ? $this->id : 0; ?>" />
                    <?php if(isset($this->story_id)){ ?>
                        <input type="hidden" name="story_id" id="story_id" value="<?php echo $this->story_id ?>" />
                   
                    <?php } ?>
                    <?php 
                        echo $this->partial('/story-content/partial/title.phtml', array('data' => $this->data, 'required' => 1)); 
                    ?>
                    <?php 
                        echo $this->partial('/story-content/partial/description.phtml', array('data' => $this->data, 'required' => 1)); 
                    ?>  
                    <?php 
                        echo $this->partial('/story-content/partial/keywords.phtml', array('data' => $this->data, 'required' => 1)); 
                    ?> 
                    <!-- Begin: CKEditor -->
                    <?php 
                        echo $this->partial('/story-content/partial/content.phtml', array('data' => $this->data, 'required' => 1)); 
                    ?>
                    <!-- End: CKEditor -->
                    <?php 
                        echo $this->partial('/story-content/partial/status.phtml', array('data' => $this->data, 'required' => 1)); 
                    ?>         
                    <?php 
                        echo $this->partial('/story-content/partial/submitbtn.phtml'); 
                    ?>
                
                </form>
            </div>
        </section>
    </div>
</div>
<?php 
    echo $this->partial('/story/partial/style.phtml'); 
?>
<?php 
    echo $this->partial('/story/partial/script.phtml'); 
?>