<form class="form-horizontal form-validate" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-sm-2 control-label">Tên <span class="required">*</span></label>
        <div class="col-sm-10">
            <input type="text" name="author" id="tag" class="form-control" required="" 
            value="<?php if(!empty($this->data['author_name'])) echo $this->data['author_name'] ?>" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Mô tả</label>
        <div class="col-sm-10">
            <input type="text" name="description" id="description" class="form-control" 
            value="<?php if(!empty($this->data['description'])) echo $this->data['description'] ?>" />
        </div>
    </div>
   
    <button type="button" name="submitButton" class="btn btn-primary" onclick="submitForm(this)">Lưu</button>
</form>