<!-- Bootstrap CSS -->    
<link href="/assets/managerapp/css/bootstrap.min.css" rel="stylesheet">
<!-- bootstrap theme -->
<link href="/assets/managerapp/css/bootstrap-theme.css" rel="stylesheet">
<!--external css-->
<!-- font icon -->
<link href="/assets/managerapp/css/elegant-icons-style.css" rel="stylesheet" />
<link href="/assets/managerapp/css/font-awesome.min.css" rel="stylesheet" />    
<link href="/assets/css/style.css" rel="stylesheet" />    
<link href="/assets/plugins/jquery-ui-1.10.4/jquery-ui-1.10.4.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/assets/managerapp/alert/dist/sweetalert.css">
<?php echo $this->headLink(); ?>
<style>
    BODY,ul.dc_mm-orange li a
    {
        font-family: Arial, Helvetica, 'sans-serif' !important;
    }
</style>