  <footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    
                    <ul>
                        <li> <a href="#"> Kiếm hiệp  </a> </li>
                        <li> <a href="#"> Tiên hiệp </a> </li>
                        <li> <a href="#"> Ngôn tình </a> </li>
                        <li> <a href="#"> Sắc hiệp </a> </li>
                   
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                  
                    <ul>
                        <li> <a href="#"> Truyện ma </a> </li>
                        <li> <a href="#"> Tiểu thuyết </a> </li>
                        <li> <a href="#"> Trinh thám </a> </li>
                        <li> <a href="#"> Võng du </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                
                    <ul>
                        <li> <a href="#"> Cổ tích việt nam </a> </li>
                        <li> <a href="#"> Cổ tích nước ngoài </a> </li>
                        <li> <a href="#"> Thần thoại </a> </li>
                        <li> <a href="#"> Dã sử </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                   
                    <ul>
                        <li> <a href="#"> Truyện hot </a> </li>
                        <li> <a href="#"> Truyện mới </a> </li>
                        <li> <a href="#"> Truyện full </a> </li>
                        <li> <a href="#"> Truyện dịch </a> </li>
                    </ul>
                </div>
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3> Lorem Ipsum </h3>
                    <ul>
                        <li>
                            <div class="input-append newsletter-box text-center">
                                <input type="text" class="full text-center" placeholder="Email ">
                                <button class="btn  bg-gray" type="button"> WEBTRUYEN <i class="fa fa-long-arrow-right"> </i> </button>
                            </div>
                        </li>
                    </ul>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-pinterest">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-youtube">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row--> 
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->
    
    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © CaoPaoLo- HUST. </p>
            <div class="pull-right">
                <ul class="nav nav-pills payments">
                	<li><i class="fa fa-cc-visa"></i></li>
                    <li><i class="fa fa-cc-mastercard"></i></li>
                    <li><i class="fa fa-cc-amex"></i></li>
                    <li><i class="fa fa-cc-paypal"></i></li>
                </ul> 
            </div>
        </div>
    </div>
    <!--/.footer-bottom--> 
</footer>