    <!-- Jumbotron Header -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox" >

          <div class="item active">
            <img src="./assets/image/naruto.jpg" alt="Chania" width="100%" style="max-height: 320px;" height="auto">
            <div class="carousel-caption">
              <h3>Naruto</h3>
              <p class="detail-caption">Naruto cửu vĩ - Naruto truyền kì.</p>
            </div>
          </div>

            <div class="item">
                <img src="./assets/image/one-piece.jpg" alt="Chania" width="100%" style="max-height: 320px;" height="auto">
                <div class="carousel-caption">
                  <h3>One Piece</h3>
                  <p class="detail-caption">Vua hải tặc - Trọn bộ</p>
                </div>
            </div>

            <div class="item">
                <img src="./assets/image/thanhgiong.jpg" alt="Chania" width="100%" style="max-height: 320px;" height="auto">
                <div class="carousel-caption">
                  <h3>Thánh Gióng</h3>
                  <p class="detail-caption">Thánh gióng - Phù Đổng Thiên Vương</p>
                </div>
            </div>

            <div class="item">
                <img src="./assets/image/trutien.jpg" alt="Chania" width="100%" style="max-height: 320px;" height="auto">
                <div class="carousel-caption">
                  <h3>Tru tiên</h3>
                  <p class="detail-caption">Tru tiên - Tiêu Đỉnh</p>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>