 <div class="col-md-3 col-sm-12">
            <div class="list-group" id="top">
                <a href="#" class="list-group-item text-center">
                    <span class="glyphicon glyphicon-star" aria-hidden="true" style="color: red"></span><b style="color: red">Truyện đang hot trong tuần</b>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
                <a href="/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html" class="list-group-item">
                Phong cách sống của người giàu  
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color: #999">123654</span>
                </a>
            </div>
            <div style="clear: both"></div>
            <div class="list-group">
                <a href="#" class="list-group-item text-center">
                    <span class="glyphicon glyphicon-star" aria-hidden="true" style="color: red"></span><b style="color: red">Truyện đang hot trong tuần</b>
                </a>
               
                <div  class="list-group-item col-md-12" onclick="location.href='/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html'">
                    <div class="row">
                        <img class="col-md-4" src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg">
                        <p class="col-md-8 " style="padding: 0px">Thần khống thiên hạ - Ngã Bản Thuần Khiết</p>
                    </div>
                </div>
                <div  class="list-group-item col-md-12" onclick="location.href='/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html'">
                    <div class="row">
                        <img class="col-md-4" src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg">
                        <p class="col-md-8 " style="padding: 0px">Thần khống thiên hạ - Ngã Bản Thuần Khiết</p>
                    </div>
                </div>
                <div  class="list-group-item col-md-12" onclick="location.href='/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html'">
                    <div class="row">
                        <img class="col-md-4" src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg">
                        <p class="col-md-8 " style="padding: 0px">Thần khống thiên hạ - Ngã Bản Thuần Khiết</p>
                    </div>
                </div>
                <div  class="list-group-item col-md-12" onclick="location.href='/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html'">
                    <div class="row">
                        <img class="col-md-4" src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg">
                        <p class="col-md-8 " style="padding: 0px">Thần khống thiên hạ - Ngã Bản Thuần Khiết</p>
                    </div>
                </div>

                <div class="list-group-item col-md-12" onclick="location.href='/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html'">
                    <div class="row">
                        <img class="col-md-4" src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg">
                        <p class="col-md-8 " style="padding: 0px">Thần khống thiên hạ - Ngã Bản Thuần Khiết</p>
                    </div>
                </div>
                <div  class="list-group-item col-md-12" onclick="location.href='/mobile-app-va-game/phong-cach-song-cua-nguoi-giau-t26.html'">
                    <div class="row">
                        <img class="col-md-4" src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg">
                        <p class="col-md-8 " style="padding: 0px">Thần khống thiên hạ - Ngã Bản Thuần Khiết</p>
                    </div>
                </div>
             
            </div>
            <div style="clear: both"></div>
         </div>