<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Content CMS">
        <meta name="author" content="TTL">
        <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive">
        <link rel="shortcut icon" href="/assets/managerapp/img/icons/favicon.png">
        <title>Content CMS</title>
        <!-- Bootstrap CSS -->    
        <link href="/assets/managerapp/css/bootstrap.min.css" rel="stylesheet">
        <!-- bootstrap theme -->
        <link href="/assets/managerapp/css/bootstrap-theme.css" rel="stylesheet">
        <!--external css-->
        <!-- font icon -->  
        <link href="/assets/managerapp/css/elegant-icons-style.css" rel="stylesheet" />
        <link href="/assets/managerapp/css/font-awesome.css" rel="stylesheet" />
        <!-- Custom styles -->
        <link href="/assets/managerapp/css/style.css" rel="stylesheet">
        <link href="/assets/managerapp/css/style-responsive.css" rel="stylesheet" />
    </head>
    <body class="login-img3-body">

        <div class="container">
            <form enctype="multipart/form-data" method="post" class="login-form" action="/manageapp/auth">        
                <div class="login-wrap">
                    <p class="login-img"><i class="icon_lock_alt"></i></p>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="icon_profile"></i></span>
                        <input type="text" class="form-control" placeholder="Username" name="username" autofocus>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="icon_key_alt"></i></span>
                        <input type="password" class="form-control" placeholder="Password" name="password">
                    </div>
                    <label class="checkbox">
                        <input type="checkbox" value="remember-me"> Remember me
                        <span class="pull-right"> <a href="#"> Forgot Password?</a></span>
                    </label>
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
                    <!-- Tam thoi bo
                    <button class="btn btn-info btn-lg btn-block" type="submit"><a href="#">Sign up</a></button>
                    -->
                </div>
            </form>
        </div>
    </body>
</html>