<div class="form-group">
    <label class="col-sm-2 control-label">CRAWLER</label>
    <div class="col-sm-10">
        <select name="crawler" id="crawler" class="form-control">
            <option <?php if (!empty($this->data) && $this->data['crawler'] == CRAWLER_ON) { ?>selected=""<?php } ?> 
            value="<?php echo CRAWLER_ON; ?>">ON</option>
            <option <?php if (!empty($this->data) && $this->data['crawler'] == CRAWLER_OFF) { ?>selected=""<?php } ?> 
            value="<?php echo CRAWLER_OFF; ?>">OFF</option>
        </select> 
    </div>
</div>