<div class="form-group">
    <label class="col-sm-2 control-label">
        Tên truyện<?php if (!empty($this->required)) { ?><span class="required">*</span><?php } ?>
    </label>
    <div class="col-sm-10">
        <input type="text" name="story_name" id="name" class="form-control" <?php if (!empty($this->required)) { ?>required=""<?php } ?> 
        value="<?php echo !empty($this->data['story_name']) ? $this->data['story_name'] : null; ?>" />
    </div>
</div>