<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Heroic Features - Start Bootstrap Template</title>
    <!-- Begin: CSS -->
        <?php require ('components/front/css.phtml');?>
        <!-- End: CSS -->
        <!-- Begin: Javascript -->
        <?php require ('components/front/javascript.phtml');?>
        <!-- End: Javascript -->
 
</head>

<body>

    <nav class="navbar navbar-default navbar-fixed-top ">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Trang chủ</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Truyện hot <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Truyện mới</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Thể loại <span class="caret"></span></a>
            <ul class="dropdown-menu category-menu">
                <li>
                    <ul class="list-unstyled col-md-6 col-sm-6">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                    </ul>
                </li>  
                <li>
                    <ul class="list-unstyled col-md-6 col-sm-6">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                    </ul>
                </li> 
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-right">
          <div class="form-group " >
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <!--slide for top focus stories -->
        <?php require ('components/front/slide-focus.phtml');?>
      
        <!-- end slide -->      
        <hr>

        <!-- Page Features -->
        <div class="col-md-9 col-sm-12">
            <div class="list-group">
                 <div class="list-group-item" style="background-color: #E6E6E6">
                    Truyện hot
                </div>
                <div class="row text-center">
            
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                </div>
            </div>
            <div style="clear: both"></div>
            <div class="list-group">
                 <div class="list-group-item" style="background-color: #E6E6E6">
                    Truyện mới cập nhật
                </div>
                <div class="row text-center">
            
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <a href="#">
                    <div class="thumbnail">
                        <img src="http://sstruyen.com/images/story/Than-Khong-Thien-Ha.jpg" alt="" style="height: 200px;">

                    </div>
                        <div class="caption">
                            <h4>Thần khống thiên hạ</h4>
                        </div>
                    </a>
                </div>
                </div>
            </div>
            <div style="clear: both"></div>
        </div>
        <!-- /.row -->
        <!-- right-tab -->
      
        <?php require ('components/front/tab-right.phtml');?>
        <!-- end righttab -->
        <hr>
        
        
      </div>
    <!--footer -->
     <?php require ('components/front/footer.phtml');?>
      
    <!--end footer -->
   


</body>

</html>
