<div class="form-group">
    <label class="col-sm-2 control-label">
        Mô tả cho avatar<?php if (!empty($this->required)) { ?><span class="required">*</span><?php } ?>
    </label>
    <div class="col-sm-10">
        <input type="text" name="avatar_description" id="avatar_description" class="form-control" <?php if (!empty($this->required)) { ?>required=""<?php } ?> 
        value="<?php echo !empty($this->data['avatar_description']) ? $this->data['avatar_description'] : null; ?>" />
    </div>
</div>