<form class="form-horizontal form-validate" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-sm-2 control-label">Tên <span class="required">*</span></label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" class="form-control" required="" 
            value="<?php if(!empty($this->data['name'])) echo $this->data['name'] ?>" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Mô tả</label>
        <div class="col-sm-10">
            <input type="text" name="description" id="description" class="form-control" 
            value="<?php if(!empty($this->data['description'])) echo $this->data['description'] ?>" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Avatar (Càng to càng tốt)</label>
        <div class="col-sm-10">
            <div class="fileinput-container">
                <input type="file" name="avatar" class="form-control" accept="image/*"/>
            </div>
            <img class="img_for_choose" id="avatar" src="<?php echo !empty($this->data['avatar_small']) ? 'http://webtruyen.vn/'.$this->data['avatar_small'] : "http://webtruyen.vn/assets/image/blank.png" ?>" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            Key words (độ dài không quá 500 ký tự)
        </label>
        <div class="col-sm-10">
            <input type="text" name="key_words" id="key_words" class="form-control" maxlength="500"
            value="<?php echo !empty($this->data['key_words']) ? $this->data['key_words'] : null; ?>" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Category truyện mới </label>
        <div class="col-sm-10">
            <select name="category_new" id="category_new" class="form-control">
                <?php if (!empty($this->listCategory)) {?>
                
                    <?php foreach ($this->listCategory as $item) {  ?>
                        <option <?php if (!empty($this->category_new) && $this->category_new['id'] == $item['id']) { ?>selected=""<?php } ?> 
                        value="<?php echo $item['id']; ?>">
                            <?php echo $item['name']; ?>
                        </option>
                    <?php } ?>
                <?php } ?>
            </select> 
        </div>
    </div>
    <button type="button" name="submitButton" class="btn btn-primary" onclick="submitForm(this)">Lưu</button>
</form>
<script type="text/javascript">
var xhr1;
$(document).ready(function(){    
    $('#key_words').tagit({
        allowSpaces: true
    });
});
</script>